### ISSUE TITLE
Issue when trying to generate

### ISSUE THREAD

**Issue by idksalem** [s0hv/rust-imgur-upload#3]
Discord Rich Presence Integration v1.3.0-beta-6+4aec8f6: artwork uploader exited with status: 1 and error: Error while parsing imgur response from 
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 client read error</title>
  </head>
  <body>
    <h1>Error 503 client read error</h1>
    <p>client read error</p>
    <h3>Error 54113</h3>
    <p>Details: cache-iad-kjyo7100155-IAD 1709593283 1886600468</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
: expected value at line 2 column 1

**Comment by s0hv** [comment]
HTTP 503 means service unavailable, so it seems that imgur or a part of it is down. Nothing that I can do about that. You just need to wait until it starts working again

**Comment by idksalem** [comment]
> HTTP 503 means service unavailable, so it seems that imgur or a part of it is down. Nothing that I can do about that. You just need to wait until it starts working again

Ohhhh okay thanks for clearing that up i see
