### ISSUE TITLE
new issue it says too many requests even though foo bar hasnt even been opened for like 3 hrs when or how do i fix

### ISSUE THREAD

**Issue by idksalem** [s0hv/rust-imgur-upload#4]
Discord Rich Presence Integration v1.3.0-beta-6+4aec8f6: artwork uploader exited with status: 1 and error: Error while parsing imgur response from {"errors":[{"id":"legacy-api-754bc898f4-p252l/82NfTz7si0-391750","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}
: missing field `data` at line 1 column 138

**Comment by s0hv** [comment]
Nothing you can do but wait

**Comment by s0hv** [comment]
The latest release should fix this issue https://github.com/s0hv/rust-imgur-upload/releases/tag/0.2.1
