### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by peytons9431** [s0hv/rust-imgur-upload#6]
from the console:

"Discord Rich Presence Integration v1.3.0-beta-6+4aec8f6: artwork uploader exited with status: 1 and error: Error while uploading to imgur: request or response body error for url (https://api.imgur.com/3/image): channel closed"

i had a similar issue in march but the updated release fixed it. seems like it has stopped working again

**Comment by peytons9431** [comment]
also, the python script seems to work completely fine, the standalone uploader is the only one that seems to be throwing errors

**Comment by s0hv** [comment]
This is a problem with imgur that I cannot fix. Building the app with your own API key will probably fix the issue
