### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by ghost** [s0hv/rust-imgur-upload#7]
Hi, I'm getting "Too Many Requests" error when I try to upload the cover url. I've tried 2 different ip: Russian and Latvian, but I still get this error.

Console output:
Discord Rich Presence Integration v1.3.0: artwork uploader exited with status: 1 and error: Error while parsing imgur response from {"errors":[{"id":"legacy-api-7756c5f445-v8sw6/FWkdEyQ56Y-1829229","code":"429","status":"Too Many Requests","detail":"Too Many Requests"}]}
: missing field `data` at line 1 column 139
x-ratelimit-clientremaining: 0
x-ratelimit-userremaining: 499
x-ratelimit-userlimit: 500

**Comment by s0hv** [comment]
This is a problem on imgurs side and I am unable to fix it
