### ISSUE TITLE
Album art is not automatically uploaded

### ISSUE THREAD

**Issue by shirafukayayoi** [s0hv/rust-imgur-upload#8]
This is the first time I have written to issues, so I'm sorry if there is something strange. I use Google Translate.
 I can't upload album art automatically from around three days ago.
 You can upload and adapt it yourself, but it's a little difficult to use.
 If there is a solution, I would like to tell you.

**Comment by Manhkbrady** [comment]
I had the same problem too, so I had to use the alternative method instead - which is to use the python script in this [doc](https://s0hv.github.io/foo_discord_rich/docs/album-artwork/#imgur-upload-script-for-python-37-or-later)
A tad bit more troublesome, but it worked for me

**Comment by JomSpoons** [comment]
Are you by chance using a VPN? I was having issues with this as well and I later realized it was because Imgur does not play nice with VPNs. If you have a VPN, either disable it while it uploads new art, or just put an exception for the EXE via split tunneling.

**Comment by s0hv** [comment]
It's a problem with the API key. I opened a support ticket but have not heard back. If imgur can't do anything about it I'll just stop trying to fix this problem.

**Comment by shirafukayayoi** [comment]
> I had the same problem too, so I had to use the alternative method instead - which is to use the python script in this [doc](https://s0hv.github.io/foo_discord_rich/docs/album-artwork/#imgur-upload-script-for-python-37-or-later) A tad bit more troublesome, but it worked for me

I made sure that this way I was moving too.
 Thanks for the best knowledge!!

**Comment by s0hv** [comment]
No response from imgur so there's nothing I can do (outside of paying for more API quota which I won't do). Best way to mitigate this is to use your own API key
